# Site settings
course_name: "R'de bulaşıcı hastalık dinamiklerini modellemeye ilişkin kısa kurs" 
course_description: "Halk sağlığı uzmanları için bulaşıcı hastalık dinamiklerinin modellenmesine yönelik eğitim kursu. Kurs, R'nin temellerini, bulaşıcı hastalıklara uygulanan matematiksel epidemiyoloji ilkelerini, bölümlü modelleri modellemeye girişi ve salgınları ve halk sağlığı müdahalelerini değerlendirmek için R'deki diğer analitik yöntemleri kapsar"
course_semester: "June 2023, Ankara"

baseurl: "/ide-modelling-R-ankara-turkish" # the subpath of your site, e.g. /blog/
url: "http://juanvesga.github.io/" # the base hostname & protocol for your site

schoolname: "Tarafından yaratıldı Juan Vesga"
schoolurl: "https://www.lshtm.ac.uk/aboutus/people/vesga.juan"
twitter_username: "@juanf_vesga"

address: |
   Juan F Vesga tarafından Türkiye Sağlık Bakanlığı (GDPH-MoH) Sağlık Güvenliği Projesi (HSP) için oluşturulmuştur. Avrupa Birliği tarafından finanse edilmekte ve Dünya Sağlık Örgütü (WHO) tarafından ülkede uygulanmaktadır.  

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Language plug in
gems:
- jekyll-language-plugin

language_data: data.lang.%%
language_includes_dir: _i18n

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
